# Generated by Django 5.2.7 on 2025-10-20 12:31

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('sector', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['ticker'],
                'indexes': [models.Index(fields=['ticker'], name='stocks_stoc_ticker_5df4c9_idx')],
            },
        ),
        migrations.CreateModel(
            name='StockData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('open', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('high', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('low', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('close', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('volume', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_data', to='stocks.stock')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moving_average', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('other_metrics', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('computed_at', models.DateTimeField(auto_now_add=True)),
                ('stockdata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='stocks.stockdata')),
            ],
            options={
                'ordering': ['-computed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='stockdata',
            index=models.Index(fields=['stock', 'date'], name='stocks_stoc_stock_i_36feb1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='stockdata',
            unique_together={('stock', 'date')},
        ),
        migrations.AddIndex(
            model_name='prediction',
            index=models.Index(fields=['stockdata'], name='stocks_pred_stockda_ba42df_idx'),
        ),
    ]
